/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;

/**
 *
 * @author Huawei
 */
public class BuatAkun extends javax.swing.JFrame {

    /**
     * Creates new form BuatAkun
     */
    public BuatAkun() {
        initComponents();
    }
    
    public void bersih(){
        TxtUser.setText("");
        TxtPw.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        TxtPw = new javax.swing.JTextField();
        BtnDaftar = new javax.swing.JButton();
        LblBack = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel1.setText("DAFTAR AKUN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel2.setText("Username :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel3.setText("Password  :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 101, -1));

        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 194, -1));

        TxtPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPwActionPerformed(evt);
            }
        });
        getContentPane().add(TxtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 194, -1));

        BtnDaftar.setBackground(new java.awt.Color(0, 153, 255));
        BtnDaftar.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        BtnDaftar.setForeground(new java.awt.Color(255, 255, 255));
        BtnDaftar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huawei\\Documents\\NetBeansProjects\\Cafe Management System\\src\\images\\save.png")); // NOI18N
        BtnDaftar.setText("DAFTAR");
        BtnDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDaftarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnDaftar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, -1));

        LblBack.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huawei\\Documents\\NetBeansProjects\\Cafe Management System\\src\\images\\exit.png")); // NOI18N
        LblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblBackMouseClicked(evt);
            }
        });
        getContentPane().add(LblBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 37, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDaftarActionPerformed
        if (TxtUser.getText().equals("")
                | TxtPw.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Semua Kolom Terlebih Dahulu!");
        } else {
            String user = TxtUser.getText();
            String pw = TxtPw.getText();

            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PertemuanKetigabelasPU");
            EntityManager em = emf.createEntityManager();
            em.getTransaction().begin();
            
            Login_1 y = em.find(Login_1.class, user);
            if (y != null) {
                JOptionPane.showMessageDialog(null, "Username sudah ada, gunakan username lain!");
                bersih();
                TxtUser.requestFocus();
            } else {
                Login_1 x = new Login_1();
                x.setUsername(user);
                x.setPassword(pw);
                em.persist(x);
                em.getTransaction().commit();
                
                JOptionPane.showMessageDialog(null, "Sukses dibuat!");
                bersih();
                
                Login z = new Login();
                z.setVisible(true);
                this.dispose();
            }
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_BtnDaftarActionPerformed

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        if (TxtUser.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Isi Username Dahulu!");
        }else{
            TxtPw.requestFocus();
        }
    }//GEN-LAST:event_TxtUserActionPerformed

    private void LblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblBackMouseClicked
        Login y = new Login();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblBackMouseClicked

    private void TxtPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPwActionPerformed
        BtnDaftar.doClick();
    }//GEN-LAST:event_TxtPwActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuatAkun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDaftar;
    private javax.swing.JLabel LblBack;
    private javax.swing.JTextField TxtPw;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
