/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Login;

import javax.swing.JOptionPane;
import javax.persistence.*;

/**
 *
 * @author Huawei
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtUser = new javax.swing.JTextField();
        TxtPw = new javax.swing.JTextField();
        LblPw = new javax.swing.JLabel();
        BtnLogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        LblBuat = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 61, 118, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 131, -1, -1));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 198, -1, -1));

        TxtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUserActionPerformed(evt);
            }
        });
        getContentPane().add(TxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 164, 260, -1));

        TxtPw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPwActionPerformed(evt);
            }
        });
        getContentPane().add(TxtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 231, 260, -1));

        LblPw.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPw.setText("Lupa Password?");
        LblPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblPwMouseClicked(evt);
            }
        });
        getContentPane().add(LblPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 259, -1, -1));

        BtnLogin.setBackground(new java.awt.Color(0, 255, 0));
        BtnLogin.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        BtnLogin.setForeground(new java.awt.Color(255, 255, 255));
        BtnLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huawei\\Documents\\NetBeansProjects\\Cafe Management System\\src\\images\\login.png")); // NOI18N
        BtnLogin.setText("LOGIN");
        BtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(BtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 287, -1, -1));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N
        jLabel5.setText("Belum punya akun?");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 321, -1, -1));

        LblBuat.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        LblBuat.setText("Buat Akun");
        LblBuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblBuatMouseClicked(evt);
            }
        });
        getContentPane().add(LblBuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 320, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUserActionPerformed
        if (TxtUser.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Username Dahulu!");
        } else {
            TxtPw.requestFocus();
        }
    }//GEN-LAST:event_TxtUserActionPerformed

    private void BtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLoginActionPerformed
        if (TxtUser.getText().equals("")
                | TxtPw.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Isi Kolom Terlebih Dahulu!");
        } else {
            EntityManagerFactory emf = Persistence.createEntityManagerFactory("PertemuanKetigabelasPU");
            EntityManager em = emf.createEntityManager();

            em.getTransaction().begin();

            String user = TxtUser.getText();
            String pw = TxtPw.getText();
            Login_1 y = em.find(Login_1.class, user);

            if (y == null) {
                JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
                TxtUser.requestFocus();
            } else if (y.getPassword().equals(pw)) {
                JOptionPane.showMessageDialog(null, "Selamat datang");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Password salah!");
                TxtPw.setText("");
                TxtPw.requestFocus();
            }
            em.getTransaction().commit();
            em.close();
            emf.close();
        }
    }//GEN-LAST:event_BtnLoginActionPerformed

    private void LblBuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblBuatMouseClicked
        BuatAkun y = new BuatAkun();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblBuatMouseClicked

    private void TxtPwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPwActionPerformed
        BtnLogin.doClick();
    }//GEN-LAST:event_TxtPwActionPerformed

    private void LblPwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblPwMouseClicked
        UbahPassword y = new UbahPassword();
        y.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LblPwMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnLogin;
    private javax.swing.JLabel LblBuat;
    private javax.swing.JLabel LblPw;
    private javax.swing.JTextField TxtPw;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
